; PlatformIO Project Configuration File for STM32 & ESP32
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev
src_dir = src
include_dir = include

; -------------------------------------------------------------
; Profile: ESP32 Wi-Fi Telemetry Gateway (Connected on COM8)
; -------------------------------------------------------------
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM8
upload_speed = 921600
monitor_port = COM8
monitor_speed = 115200
build_src_filter = +<main_esp32.cpp> -<main_stm32.cpp>

; -------------------------------------------------------------
; Profile: STM32 Blue Pill ST-Link V2 (SWD Programmer)
; -------------------------------------------------------------
[env:bluepill_f103c8_stlink]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = stlink
monitor_speed = 9600
lib_deps =
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.8
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
    -D USBD_VID=0x0483
    -D USBD_PID=0x5740
build_src_filter = +<main_stm32.cpp> -<main_esp32.cpp>

; -------------------------------------------------------------
; Profile: STM32 Blue Pill Serial / USB-UART
; -------------------------------------------------------------
[env:bluepill_f103c8_serial]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_protocol = serial
upload_port = COM3
monitor_speed = 9600
lib_deps =
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.8
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
    -D USBCON
build_src_filter = +<main_stm32.cpp> -<main_esp32.cpp>
